apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nebula
  annotations:
    description: 'Order creation with complex compositions'
spec:
  components:
    # Gateway component for processing HTTP requests,
    # routing them to appropriate services
    - name: gateway
      type: component
      properties:
        image: file://./bin/gateway.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100
        - type: link
          properties:
            target: pricing
            namespace: nebula
            package: pricing
            interfaces: [pricing-api]
        - type: link
          properties:
            target: inventory
            namespace: nebula
            package: inventory
            interfaces: [inventory-api]
    
    # Pricing component for calculating order prices,
    # taking into account VAT and currency rates
    - name: pricing
      type: component
      properties:
        image: file://./bin/pricing.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100

    # Inventory component for managing stock levels,
    # ensuring items are available for orders
    - name: inventory
      type: component
      properties:
        image: file://./bin/inventory.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 100

    # HTTP Server Capability
    - name: server
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        config:
        - name: http-config
          properties:
            routing_mode: address
            default_address: '0.0.0.0:8080'
      traits:
        - type: link
          properties:
            target: gateway
            namespace: wasi
            package: http
            interfaces: [incoming-handler]