package nebula:otel-framework;

world otel {
    import wasi:random/random@0.2.10;
    import wasi:clocks/wall-clock@0.2.0;

    import wasi:otel/types@0.3.0;
    import wasi:otel/tracing@0.3.0;
    // import wasi:otel/types@0.3.0;
    // import wasi:otel/tracing@0.3.0;
}