package nebula:matcher;

world matcher {
    // Goofy workaround which I don't understand, pain
    include wasi:clocks/imports@0.2.10;
    include wasi:io/imports@0.2.10;

    import nebula:demo/driver;
    export nebula:demo/matcher;
}