// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
#ifndef __BINDINGS_DATABASE_ENGINE_H
#define __BINDINGS_DATABASE_ENGINE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct database_engine_string_t {
  uint8_t*ptr;
  size_t len;
} database_engine_string_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} database_engine_list_u8_t;

// Imported Functions from `wasi:random/random@0.2.0`
// Return `len` cryptographically-secure random or pseudo-random bytes.
// 
// This function must produce data at least as cryptographically secure and
// fast as an adequately seeded cryptographically-secure pseudo-random
// number generator (CSPRNG). It must not block, from the perspective of
// the calling program, under any circumstances, including on the first
// request and on requests for numbers of bytes. The returned data must
// always be unpredictable.
// 
// This function must always return fresh data. Deterministic environments
// must omit this function, rather than implementing it with deterministic
// data.
extern void wasi_random_random_get_random_bytes(uint64_t len, database_engine_list_u8_t *ret);
// Return a cryptographically-secure random or pseudo-random `u64` value.
// 
// This function returns the same type of data as `get-random-bytes`,
// represented as a `u64`.
extern uint64_t wasi_random_random_get_random_u64(void);

// Exported Functions from `nebula:inventory/database-engine`
uint32_t exports_nebula_inventory_database_engine_get_stock_level(database_engine_string_t *sku, database_engine_string_t *warehouse_id);

// Helper Functions

void database_engine_list_u8_free(database_engine_list_u8_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void database_engine_string_set(database_engine_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void database_engine_string_dup(database_engine_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void database_engine_string_free(database_engine_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
