package nebula:gateway;

world gateway {
    import nebula:core/types;
    import nebula:inventory/inventory-api;
    import nebula:pricing/pricing-api;
    import wasi:logging/logging@0.1.0-draft;
    export wasi:http/incoming-handler@0.2.8;
}