package nebula:warehouse-engine;

world warehouse-engine {
    import wasi:filesystem/preopens@0.2.0;
    import wasi:filesystem/types@0.2.0;
    import wasi:logging/logging@0.1.0-draft;
    import wasi:io/streams@0.2.0;
    import nebula:inventory/database-engine;
    export nebula:inventory/warehouse-engine;
}